FROM ubuntu

RUN apt-get update
RUN apt-get install -y less
RUN apt-get install -y htop
RUN apt-get install -y vim
RUN apt-get install -y gnuplot
RUN apt-get install -y python2.7
RUN apt-get install -y python-pip
RUN pip install futures
RUN pip install requests
RUN pip install eventlet

